# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-19 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expert_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=100)),
                ('order_state', models.IntegerField(choices=[(0, 'Publish'), (1, 'Picked'), (2, 'Finished'), (3, 'Evaluated')], default=0)),
                ('order_sum', models.FloatField(default=0.0)),
                ('order_location', models.CharField(max_length=255)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('picked_time', models.DateTimeField(null=True)),
                ('finished_time', models.DateTimeField(null=True)),
                ('evaluation', models.TextField(null=True)),
                ('grade', models.PositiveIntegerField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish_order', to='expert_user.ExUser')),
                ('picker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picked_order', to='expert_user.ExUser')),
            ],
            options={
                'ordering': ['-publish_time', 'id'],
            },
        ),
    ]
