# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-19 10:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=20, null=True, unique=True)),
                ('qq', models.CharField(max_length=20, null=True, unique=True)),
                ('we_chat', models.CharField(max_length=30, null=True, unique=True)),
                ('sex', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Secret')], default=2)),
                ('age', models.PositiveIntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, upload_to='/avatar/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
