# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-19 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exuser',
            name='avg_grade',
            field=models.FloatField(default=0.0),
        ),
    ]
