# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-19 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_skill', '0002_auto_20180419_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['need_top', 'is_system', 'id']},
        ),
        migrations.AddField(
            model_name='skill',
            name='is_system',
            field=models.BooleanField(default=True),
        ),
    ]
