# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-19 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_user', '0002_exuser_avg_grade'),
        ('expert_skill', '0003_auto_20180419_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ManyToManyField(related_name='skill', to='expert_user.ExUser'),
        ),
    ]
